- back/src/main/java/travelRepo/domain/account/controller/AccountController.java
- back/src/main/java/travelRepo/domain/account/service/AccountService.java
- back/src/main/java/travelRepo/domain/board/entity/Board.java
- back/src/main/java/travelRepo/domain/board/entity/BoardPhoto.java
- back/src/main/java/travelRepo/domain/board/entity/BoardTag.java
- back/src/main/java/travelRepo/domain/board/entity/Tag.java
- back/src/main/java/travelRepo/domain/board/repository/BoardPhotoRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardTagRepository.java
- back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java
- back/src/main/java/travelRepo/domain/follow/repository/FollowRepository.java
- back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
- back/src/main/resources/static/db/data.sql
- back/src/main/resources/static/docs/index.html
- back/src/test/resources/static/db/data.sql
Account 삭제 API를 구현했습니다.
1. account와 연관관계에 있는 엔티티를 차례대로 삭제한 후, account를 삭제하였습니다.
2. 삭제는 bulk 연산을 통해 delete를 한번에 처리하도록 각 repository에 메서드를 작성하고 사용하였습니다. 
추가 변경
1. Board를 삭제할 때 photo가 삭제되지 않는 문제가 있어서 JoinTable역할을 할 BoardPhoto를 생성하였습니다.
2. Board_Tag -> boardTag로 변경했습니다.
3. 삭제 테스트를 하기 위해 어플리케이션과 테스트에 초기 데이터를 추가하였습니다.
> [Feat] Account 삭제 API 구현

- back/src/main/java/travelRepo/domain/board/controller/BoardController.java
- back/src/main/java/travelRepo/domain/board/dto/BoardAddReq.java
- back/src/main/java/travelRepo/domain/board/dto/BoardModifyReq.java
- back/src/main/java/travelRepo/domain/board/entity/Board.java
- back/src/main/java/travelRepo/domain/board/entity/BoardPhoto.java
- back/src/main/java/travelRepo/domain/board/entity/BoardTag.java
- back/src/main/java/travelRepo/domain/board/repository/BoardPhotoRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardTagRepository.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/java/travelRepo/global/exception/ExceptionCode.java
- back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
1. 게시글을 수정하는 API를 구현했습니다.
- 로그인한 계정과 수정하려는 게시글을 등록한 계정이 다른 경우 에러가 발생합니다.
- 태그/이미지의 경우 수정될 데이터가 존재하면 기존의 데이터를 전부 지우고 새롭게 등록하는 방식으로 수정됩니다.
2. 게시글 수정 API 테스트 코드를 작성했습니다.
> [Feat] 게시글 수정 API 구현 및 테스트

- front/src/component/common/Post.jsx
- front/src/component/main/MainContents.jsx
- front/src/component/main/MainSort.jsx
- front/src/component/main/MainTheme.jsx
- front/src/pages/MainPage.jsx
- Post 공통 컴포넌트화
`경호님이 작업하신 Post 컴포넌트 일부 수정하여 공통 컴포넌트화 했습니다.`
- 메인페이지 구성 컴포넌트 레이아웃, 스타일 적용
`Sort 컴포넌트는 테마와 같은 라인에서는 어떤 방법을 적용해도 겹쳐서 그냥 아래로 뺐습니다.`
- 해상도가 줄어들때마다 컨텐츠도 줄어들도록 반응형 형태로 적용
- 아래 해상도 기준 화면에 보이는 `Post` 개수가 달라지도록 미디어쿼리 적용
`1920px~1441px : 4개 / 1440px~1025px : 3개 / 1024px~550px: : 2개 / 549px~ : 1개`
> [Feat] 메인페이지 레이아웃/스타일 적용

- back/src/main/java/travelRepo/domain/account/dto/AccountSummaryRes.java
- back/src/main/java/travelRepo/domain/board/controller/BoardController.java
- back/src/main/java/travelRepo/domain/board/dto/BoardDetailsRes.java
- back/src/main/java/travelRepo/domain/board/entity/Board.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/resources/static/docs/index.html
- back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
1. 게시물 단일 조회 API를 구현했습니다. 
- 게시물 조회 시 views가 변하기 때문에 LastmodifiedAt의 값이 변하지만 사용되는 부분이 없기 때문에 일단 그대로 뒀습니다.
- 게시물 조회 시 해당 게시물이 로그인한 계정이 작성한 것인지 판별하는 myBoard 값을 응답 데이터에서 삭제했습니다.
2. 게시물 단일 조회 API 테스트 코드를 작성했습니다.
3. 응답 데이터에 변화가 있기 때문에 API 명세서를 최신화 했습니다.
> [Feat] 게시물 단일 조회 API 구현 및 테스트

- back/src/main/java/travelRepo/domain/comment/controller/CommentController.java
- back/src/main/java/travelRepo/domain/comment/dto/CommentAddReq.java
- back/src/main/java/travelRepo/domain/comment/entity/Comment.java
- back/src/main/java/travelRepo/domain/comment/service/CommentService.java
- back/src/main/java/travelRepo/global/exception/advice/ExceptionAdvice.java
- back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java
댓글 등록 API 와 테스트 코드를 작성했습니다.
댓글은 게시글과 다르게 JSON 형식으로 데이터를 받아 @RequestBody를 사용하기 때문에 MethodArgumentNotValidException룰 캐치할 수 있는 ExceptionHandler를 추가했습니다.
> [Feat] 댓글 등록 API 구현 및 테스트

- back/src/main/java/travelRepo/domain/board/controller/BoardController.java
- back/src/main/java/travelRepo/domain/comment/controller/CommentController.java
- back/src/main/java/travelRepo/domain/comment/dto/CommentDetailsRes.java
- back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java
- back/src/main/java/travelRepo/domain/comment/service/CommentService.java
- back/src/main/java/travelRepo/global/common/dto/SliceDto.java
- back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java
- back/src/test/resources/static/db/data.sql
특정 게시글의 전체 댓글을 조회할 수 있는 API를 구현/테스트 했습니다.
- 기본적으로 5개 씩 조회할 수 있도록 했습니다 .
- 생성 순 (오래된 댓글 순)으로 정렬되도록 했습니다.
- boardId를 검증하는 로직은 넣지 않았습니다. 백엔드 쪽에서 검증하는 건 크게 의미 없고 프론트 쪽에서 주의해야 할 부분이라 생각합니다.
> [Feat] 댓글 조회 API 구현 및 테스트

- front/src/component/publish/PublishForm.jsx
- front/src/component/publish/PublishPhoto.jsx
사진 업로드 시 blob의 url을 임시 생성해 로컬에서 미리보기를 보여줍니다.
FileReader라는 메서드도 있는데 base64 방식이라 createObjectUrl 썼습니다.
속도는 빠르지만 일일이 메모리에서 삭제 해줘야하는 번거로움이 있어요ㅠㅠ
여튼 현재는 유저 윈도우 메모리 활용하는 방식인데 나중에 서버 전송이 추가된다면
각 img요소의 src속성을 임시 url => 백엔드 url로 대체하면 되지 않을까? 생각하고 있습니다..
라이브러리 없이 해보려니 어렵네요 많은 도움 부탁드려요!
TODO : 서버 전송, 에러 처리(갯수/사이즈 등), 삭제버튼 개별 적용, 버그 픽스, CSS 🥶..
> [Feat] 게시글 작성 페이지 이미지 미리보기

- front/package-lock.json
- front/package.json
- front/src/App.js
- front/src/api/loginUserApi.js
- front/src/component/common/header/HeaderUser.jsx
- front/src/component/common/modal/LoginModal.jsx
- front/src/redux/action/loginAsync.js
- front/src/redux/loginSlice.js
- front/src/redux/store.js
- front/src/util/cookie.js
로그인 성공과 실패에 따른 응답을 서버에서 받아 알맞은 UI를 출력하도록 했습니다.
로그인 성공시 헤더에 임시로 사용할 로그아웃 버튼을 달아놓았습니다.
로그인에 성공하면 jwt가 세션 쿠키에 담깁니다.
토큰이 필요한 요청을 보내실 때 꺼내 쓰시면 됩니다.
> [Feat] 로그인 성공, 실패에 따른 분기 및 UI 추가, 임시 로그아웃 버튼 구현

- front/src/App.js
- front/src/component/common/header/HeaderUser.jsx
- front/src/redux/loginModalSlice.js
- front/src/redux/store.js
로그인 모달 상태 redux에서 관리하도록 변경, 프로필 이미지 헤더에 반영
다만 프로필 이미지 헤더에 반영되는 기능은 로그인 후 relocate 이 되야 반영이됩니다.
> [Feat] 로그인 모달 상태 redux에서 관리하도록 변경, 프로필 이미지 헤더에 반영

- front/src/api/hookApi.js
- front/src/api/postDetailApi.js
- front/src/component/common/like/Like.jsx
- front/src/component/common/modal/LoginModal.jsx
- front/src/component/postDetail/PostDetailArticle.jsx
- front/src/component/postDetail/PostDetailMain.jsx
- front/src/hooks/useAxios.jsx
- front/src/hooks/useInput.jsx
1. 로그인 모달 페이지 리로딩 추가
2. 커스텀 훅 useInput, useAxios 추가
3. 상세화면 로그인 여부에 따른 좋아요 및 팔로우 기능 사용 및 금지
4. 게시글 삭제 로직
1. 사용자 프로필 클릭 시 사용자의 계정으로 이동
2. 태그 클릭 시 해당 태크로 검색
3. toast 로 추후 에러 로직 처리
> [Feat] 게시글 상세화면 로그인 여부에 따른 로직 구현

- back/src/main/java/travelRepo/domain/board/dto/BoardAddReq.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/java/travelRepo/domain/comment/service/CommentService.java
Board 에 태그/ 사진 추가 시 재사용 검증 로직에서 BoardTag와 BoardPhoto를 db가 아닌 Board에 있는 list에서 조회하도록 수정했습니다.
> [Fix] 게시글에 태그/사진 추가 로직 수정

- back/src/main/java/travelRepo/domain/board/repository/BoardPhotoRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardTagRepository.java
- back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java
- back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
@Modifying 어노테이션의 attribute를 수정하면서 게시글이 삭제되지 않는 문제가 있었습니다.
clearAutomatically이 필요하지 않아보여 삭제했었는데 orphanRemoval 옵션과 문제가 생겨 다시 넣어주었습니다.
> [Fix] 게시글이 삭제되지 않는 오류 수정

- front/package-lock.json
- front/package.json
- front/src/component/common/LoadingSpinner.jsx
- front/src/hooks/useIntersect.js
- front/src/pages/mainPages/AllThemePage.jsx
- front/src/pages/mainPages/MainPage.jsx
- front/src/pages/mainPages/RestaurantPage.jsx
- front/src/pages/mainPages/SpotPage.jsx
- front/src/pages/mainPages/StayPage.jsx
📍 각 테마 페이지의 무한스크롤 로직을 Hook으로 변경
📍 `useIntersect` **Hook 추가 사항**
- 인자로 `threshold` 옵션 추가
- 다음페이지가 없을 경우 `target`을 숨기는 로직 추가
📍 **로딩스피너**
- 데이터 요청시 pending 상태일 때 `로딩중..` 임시 텍스트가 표시되도록 추가
- `React Spinners` **라이브러리 사용 협의 후 로딩스피너 추가 예정**
📍 Hook의 추가 사항은 이미 사용중인 컴포넌트에 영향이 없을 것으로 보여서 급한 마음에 임의로 추가하였습니다. 혹시 문제가 될 것 같으면 코멘트 주세요😭
> [Feat] 무한스크롤 Hook 적용 및 로딩스피너 추가

- front/src/component/common/Post.jsx
게시물의 태그가 1개만 있는 경우 화면을 줄일 때 메인페이지의 Post의 태그가 사라지는 버그를 수정했습니다.
> [Fix] 태그가 1개일 때 사라지는 버그 수정

- back/src/docs/asciidoc/index.adoc
- back/src/main/java/travelRepo/domain/board/controller/BoardController.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
- back/src/main/resources/static/docs/index.html
- back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
- back/src/test/resources/static/db/data.sql
1. 좋아요한 게시글을 조회하는 방법을 기존 LikeRepository에서 조회하는 방법에서 BoardRepository에서 outer join을 통해 조회하는 방법으로 수정했습니다.
- page, size는 파라미터로 받을 수 있지만 정렬은 최근 좋아요를 누른 순으로 고정했습니다.
2. 좋아요한 게시글 조회 API를 테스트하고 명세서에 추가했습니다.
> [Refactor] 좋아요한 게시글 조회 API 로직 변경/ 테스트/ API 문서화

- back/src/main/java/travelRepo/domain/board/repository/BoardRepositoryImpl.java
게시글 추천/조회 순으로 전체 조회 시 서로 다른 페이지에서 게시글이 중복으로 조회되는 문제가 있었습니다.
아직 정확한 원인은 파악하지 못했지만 게시글, 조회수는 중복되는 값이 많아 정렬이 유일하게 결정되지 않는 것이 문제 같아 우선 정렬 조건을 추가했습니다.
> [Fix] 게시글 조회시 중복되어 조회되는 문제 수정

- front/src/component/main/MainSort.jsx
- front/src/component/publish/PublishForm.jsx
- front/src/hooks/useIntersect.js
- front/src/pages/mainPages/AllThemePage.jsx
- front/src/pages/mainPages/RestaurantPage.jsx
- front/src/pages/mainPages/SpotPage.jsx
- front/src/pages/mainPages/StayPage.jsx
1. use옵저버 정렬을 사용함에 따른 수정
2. 조회수가 2회씩 증가하는 부분 수정
3. 전체 및 테마별 정렬 기능 추가
4. 정렬 중복 클릭 방지 추가
1. 현재 조회순 및 추천순 데이터가 중복으로 들어오는 부분이 발생하여 백엔드 쪽에서 수정을 해줘야 한다. (백엔드와 이야기 완료)
옵저버에 대해서 문의가 있으신분은 말씀해주세요
> [Feat] 정렬기능 추가

- front/src/App.js
- front/src/component/common/Loading.jsx
- front/src/component/common/LoadingSpinner.jsx
> [Fix] 메인페이지 lazy 삭제 및 로딩스피너 통일

- front/src/pages/mainPages/MainPage.jsx
- front/src/pages/myPages/MyLikes.jsx
- front/src/pages/myPages/MyPost.jsx
데이터가 5개 미만일 때 메인페이지, 마이페이지의 게시글탭, 좋아요탭의 레이아웃이 유지되도록 수정하였습니다.
> [Fix] 데이터가 5개 미만일 때 레이아웃 유지하도록 수정

- back/src/docs/asciidoc/index.adoc
- back/src/main/java/travelRepo/domain/board/controller/BoardController.java
- back/src/main/java/travelRepo/domain/board/dto/BoardDetailsRes.java
- back/src/main/java/travelRepo/domain/board/dto/BoardListReq.java
- back/src/main/java/travelRepo/domain/board/dto/BoardSummaryRes.java
- back/src/main/java/travelRepo/domain/board/dto/BoardSummaryResWithLikeId.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepositoryCustom.java
- back/src/main/java/travelRepo/domain/board/repository/BoardRepositoryImpl.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/java/travelRepo/domain/comment/controller/CommentController.java
- back/src/main/java/travelRepo/domain/comment/dto/CommentDetailsRes.java
- back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java
- back/src/main/java/travelRepo/domain/comment/service/CommentService.java
- back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
- back/src/main/resources/static/docs/index.html
- back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
- back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java
무한스크롤이 적용되는 API의 페이지네이션을 offset 방식에서 cursor 방식으로 변경했습니다. 현재는 이전 방식과 바뀐 방식 모두 지원하도록 했고, 프론트 분들께서 요청 데이터를 변경하면 기존 방식은 삭제할 예정입니다.
cursor 방식의 페이지네이션을 적용하기 위해 응답 데이터를 추가했습니다.
- 게시글 조회/검색 응답 데이터에 조회수를 추가했습니다.
- 좋아요한 게시글 응답 데이터를 분리하고 likdId를 추가했습니다.
변경된 API에 맞춰 테스트와 명세서를 수정했습니다.
> [Refactor] 무한스크롤 페이지네이션 방식 변경

- back/src/main/java/travelRepo/domain/account/repository/AccountRepositoryImpl.java
Follow 회원 조회 시, totalElement가 페이지에 조회된 회원의 수로 나오는 것을 변경했습니다.
카운트 쿼리를 작성하지 않아서 발생한 문제였습니다.
이제 Follow한 전체 회원을 표기하도록 변경됬습니다.
> [Fix] Follow 회원 조회 시, totalElement가 전체 회원의 수로 나오도록 수정

- front/src/component/common/header/HeaderDropDownItem.jsx
- front/src/component/follow/FollowList.jsx
- front/src/component/follow/FollowPost.jsx
- front/src/component/follow/FollowUserCard.jsx
- front/src/pages/myPages/MyFollower.jsx
- front/src/pages/myPages/MyFollowing.jsx
- front/src/pages/myPages/MyLikes.jsx
- front/src/pages/myPages/MyPage.jsx
- front/src/pages/myPages/MyPost.jsx
css는 아까 회의시간에 보여드린 것에서 수정하지 않았습니다.
360px 이하로 내려가면 유저프로필만 나오게 해보려했는데, 유저 프로필에 center 가 안먹어서 이것 저것 시도해보았습니다만 잘 안풀려서, 우선 이대로 마무리하고, 지금 급한 회원가입 약관, 로그인모달, 로그아웃 문제를 해결해야 할 것 같습니다.
기본적인 반응형과, props와 컴포넌트간 연결, 팔로우 팔로잉 버튼은 마무리 해놓았습니다.
아래에 완성도를 높이기위해 해야할 목록 적어놓았습니다. 
Todo
1. 반응형 360px 이하로 내려가면 유저프로필만 나오게 하는 부분,
2. 타회원정보 페이지 추가되면 유저 카드 눌렀을 때, 해당 유저페이지로 이동되게 하는 부분,
3. 팔로우 팔로잉 탭에서 언팔하거나 팔로우하면 현재는 리로딩되면서 데이터 갱신과 함께 리랜더링이 이루어지는데,
리로드 없이 리랜더링을 할 수 있는 방법이 있다면 해당 방법 적용.
> [Feat] 내정보-팔로워, 팔로잉 탭 반응형, 데이터 연결 및 팔로우 팔로잉 버튼 연결

- front/src/App.js
- front/src/api/myInfoEditApi.js
- front/src/component/myInfoEdit/MyInfoEditContent.jsx
- front/src/component/myInfoEdit/MyInfoEditForm.jsx
- front/src/component/myInfoEdit/MyInfoEditProfile.jsx
- front/src/component/userInfo/UserInfoCard.jsx
- front/src/pages/myPages/MyInfoEdit.jsx
- 프로필사진, 닉네임(중복값 검사 포함), 비밀번호, 자기소개 수정
- 사진은 계속 여러개 등록해도 가장 최근 것만 반영되고 카메라 아이콘이 등록버튼입니다.
- 수정하지 않고 등록한 항목은 기존 정보가 유지됩니다.
- 렌더링은 createObjectURL말고 FileReader readAsDataURL 메서드 궁금해서 사용해봤습니다.
- 느린 대신 메모리 관리가 자동으로 된다는데 프로필은 사진 한장이라 체감은 크게 안되네요.
작동 안되는 부분 있으시면 알려주세요!
*Todo : 회원탈퇴버튼 추가
> [Feat] 내정보 수정 화면 제작

- front/src/component/common/header/HeaderDropDownItem.jsx
로그아웃 핸들러 버그 수정
removeCookie에 옵션 넣었습니다. 이것때문일지도 모른다고 생각해서요.
쿠키 삭제 후 리로딩이 되는 것이 아니고, dipatch를 통해 로그아웃 상태를 갱신시켜준 뒤, navigate를 통해 메인으로 이동시켰습니다.
일단 버그의 원인으로 의심되는 것은 위 두 가지 였고, 제가 테스트 했을 때엔 문제 없었습니다.
로그인 후, 마이페이지나 다른 페이지 들어가보신 다음, 새로고침 누르시고 이것저것 다른 동작도 해보신 뒤에, 로그아웃이 정상적으로 된다면 문제가 없는 것으로 간주해도 될 것 같습니다.
> [Fix] 로그아웃 핸들러 버그 수정

- front/src/component/common/Post.jsx
- front/src/component/main/MainSort.jsx
기존에는 최대 3개까지 태그를 표시하도록 하였으나 등록된 태그를 모두 표시하도록 수정하였습니다.
Post의 크기가 줄어 태그를 모두 표시하지 못할 경우 마지막 태그부터 말줄임 되도록 하였습니다.
> [Refactor] Post의 태그를 모두 보여주도록 수정

- back/src/main/java/travelRepo/domain/board/dto/BoardAddReq.java
- back/src/main/java/travelRepo/domain/board/dto/BoardModifyReq.java
- back/src/main/java/travelRepo/global/exception/ExceptionCode.java
- back/src/main/java/travelRepo/global/image/service/ImageService.java
- back/src/test/java/travelRepo/global/image/controller/ImageControllerTest.java
Image validation을 추가하였고 그에 따른 테스트도 추가하였습니다.
jpg, jpeg, png의 확장자만 받을 수 있도록 변경하였습니다.
확장자를 제외한 파일이름의 형식에도 제한을 걸어놨습니다.
파일 이름은 공백으로만 이루어지는 경우만을 제한하였습니다.
ex) "    .jpg"
추가 변경
1. 프런트와 맞춰 board의 content의 최대 자수를 2000자로 제한 하였습니다. 
: boardAddReq, boardModifyReq에 적용하였습니다.
> [Fix] Image validation 추가

- back/src/main/java/travelRepo/domain/account/dto/FollowAccountDetailsRes.java
- back/src/main/java/travelRepo/domain/account/service/AccountService.java
- back/src/main/java/travelRepo/domain/board/service/BoardService.java
- back/src/main/java/travelRepo/global/cache/CacheConfig.java
- back/src/main/java/travelRepo/global/cache/CacheEvent.java
- back/src/main/java/travelRepo/global/cache/CacheProcessor.java
- back/src/test/java/travelRepo/domain/account/controller/AccountCacheTest.java
- back/src/test/java/travelRepo/domain/board/controller/BoardCacheTest.java
- back/src/test/java/travelRepo/util/After.java
cache와 관련해서 서버구동중 발생하는 이벤트를 처리하는 Class인 cacheEvent를 생성했습니다.
서버가 시작될 때, 1시간마다 view를 업데이트하고 redis를 초기화하는 메서드를 해당 클래스에서 처리하도록 하였습니다.
추가적으로, cache와 관련된 test코드를 작성하였습니다. 회원 또는 게시물을 단일 조회 했을 때, 캐시가 잘 저장 되는지, 
수정과 삭제를 했을 때 관련된 캐시가 잘 삭제되는지를 테스트 하였습니다.
또한 모든 테스트 케이스마다 redis가 초기화되는 로직을 After 객체에 작성하였습니다.
추가 변경
1. 팔로우 회원 조회 시 회원이 작성한 게시물 수를 6개로 변경하였습니다.
> [Refactor] cacheEvent 구조 변경

- front/src/component/myInfoEdit/MyInfoEditProfile.jsx
- front/src/component/publish/PublishPhoto.jsx
Format을 "All files"로 하면 일부 확장자명(gif 등) 등록 가능했던 부분 막았습니다.
글작성,프로필사진에 적용했고 저는 webp, gif, bmp, avif 등 테스트 해봤는데 머지되면 한번씩 확인 부탁드릴게요
@hipopotamus
> [Feat] 사진 등록 미지원 확장자 차단 및 안내 메세지 추가

- front/src/component/userInfo/UserInfo.jsx
팔로워,팔로잉 탭에서 유저카드 클릭시 userinfo가 갱신되지않는 현상 수정
userInfo의 useEffect 종속성 배열에 accountId 가 추가되지 않아 발생하는 현상이였습니다.
> [Fix] 팔로워,팔로잉 탭에서 유저카드 클릭시 userinfo가 갱신되지않는 현상 수정

- back/build.gradle
- back/src/main/java/travelRepo/global/image/repository/FolderImageRepository.java
- back/src/main/java/travelRepo/global/image/repository/ImageRepository.java
- back/src/main/java/travelRepo/global/image/repository/S3ImageRepository.java
- back/src/main/java/travelRepo/global/image/service/ImageService.java
1. 썸네일 이미지 생성 시 이미지가 회전하는 현상을 수정했습니다.
- 이미지 저장 시 사진의 메타 데이터에 있는 방향 정보(int)를 읽어와 파일명 앞에 추가했습니다.
- 썸네일 이미지 생성 시 이 방향 정보를 통해 이미지를 올바른 방향으로 회전시킨 후 썸네일을 생성하도록 수정했습니다. 
2. S3ImageRepositody와 FolderImageRepository의 중복되는 로직을 ImageService로 이동시켰습니다.
> [Fix] 썸네일 이미지 회전하는 현상 수정

- front/src/component/common/Pagination.jsx
5의 배수 페이지를 선택할 경우 다음 페이지 그룹으로 바뀌는 현상을 수정하였습니다.
> [Fix] 페이지네이션 로직 수정

- front/src/component/myInfoEdit/MyInfoEditContent.jsx
- front/src/component/myInfoEdit/MyInfoEditDelete.jsx
- 회원탈퇴버튼 길이 css 재설정
- 탈퇴/수정완료때 뜨는 확인 모달 =>  확인을 눌러야 다음 페이지로 이동 (실제 동작은 모달 오픈 시키면서 이뤄짐)
> [Fix] 내정보수정 페이지 탈퇴버튼, 모달작동 수정

- front/src/component/common/EmptyText.jsx
- front/src/component/common/Pagination.jsx
- front/src/component/follow/FollowList.jsx
- front/src/component/follow/FollowUserCard.jsx
- front/src/component/postDetail/PostDetailArticle.jsx
- front/src/component/userInfo/UserInfoCard.jsx
- front/src/pages/myPages/MyFollower.jsx
- front/src/pages/myPages/MyFollowing.jsx
- front/src/pages/myPages/MyLikes.jsx
- front/src/pages/myPages/MyPost.jsx
- 게시글, 좋아요, 팔로워, 팔로잉 페이지의 데이터가 없는 경우 해당하는 문구 표시
- 팔로워, 팔로잉 유저의 게시글이 없는 경우 해당하는 문구 표시
- 팔로워, 팔로잉 데이터가 업는 경우 페이지네이션 숨김
- 마이페이지 내 모든 컴포넌트의 nickname에 말줄임, 폰트 사이즈 조정, 너비 설정 등 css 수정
> [Feat] 마이페이지의 본문 데이터가 없는 경우

- front/src/component/common/header/Header.jsx
- front/src/component/common/header/HeaderUser.jsx
- front/src/component/postDetail/PostDetailArticle.jsx
- front/src/component/postDetail/comment/CommentMore.jsx
- front/src/component/postDetail/comment/CommentWrite.jsx
- front/src/pages/mainPages/MainPage.jsx
- front/src/pages/myPages/MyLikes.jsx
- front/src/pages/myPages/MyPost.jsx
- 무한스크롤 적용 페이지들 좌우 여백이 적용되지 않고 있어서 수정했습니다.
- 게시글 상세페이지의 이미지들에 `object-fit: cover` 적용했습니다.
- 상세페이지 댓글창의 '댓글을 달아주세요' 텍스트에 549px이하일 때 font-size 조정했습니다.
- pc버전 로고에 불필요한 크기가 적용되어있어 수정했습니다.
- 게시글 작성 버튼에 적용된 크기가 `min-width` 때문에 적용되지 않고 있어서 수정했습니다.
> [Fix] 누락된 css 적용 및 수정

- front/src/App.js
- front/src/api/loginUserApi.js
- front/src/component/common/modal/LoginModal.jsx
- front/src/pages/OauthPage.jsx
구글 소셜로그인 추가
로그인 모달에서 소셜로그인 버튼을 누르면 google oauth 페이지로 이동합니다.
google 인증을 완료하면 백엔드에서 클라이언트의 oauth 페이지로 리디렉션 시켜줍니다.
oauth 페이지에서 url에 있는 jwt를 쿠키에 저장하고, 로그인 유저조회 api를 실행하고, 로그인 상태를 true로 바꾼 뒤, 메인으로 이동시킵니다.
> [Feat] 구글 소셜로그인 추가

- front/src/component/postDetail/PostDetailMain.jsx
- front/src/component/postDetail/PostDetailPhoto.jsx
- front/src/component/postDetail/comment/CommentMore.jsx
- front/src/component/postDetail/comment/CommentWrite.jsx
1. 댓글 수정시 글자수 표시
2. 댓글 250자를 전부 작성시 빨간색으로 강조 표시
3. 로딩 함수 위치 변경
4. 게시물이 존재하지 않을 경우에만 에러 페이지로 이동
5. 댓글 입력시 전송 중일 경우에는 다시 전송을 못하도록 막음
> [Fix] 댓글 수정시 글자수 제한 및 로딩함수 위치 변경
