back/src/docs/asciidoc/index.adoc, back/src/main/java/travelRepo/domain/comment/controller/CommentController.java, back/src/main/java/travelRepo/domain/comment/dto/CommentAddReq.java, back/src/main/java/travelRepo/domain/comment/dto/CommentDetailsRes.java, back/src/main/java/travelRepo/domain/comment/dto/CommentListReq.java, back/src/main/java/travelRepo/domain/comment/dto/CommentModifyReq.java, back/src/main/java/travelRepo/global/security/config/SecurityConfig.java, back/src/main/resources/static/docs/index.html, back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java
1. 로그인 없이 댓글을 조회할 수 있도록 권한을 수정했습니다.
2. 댓글 mock API를 구현하고 문서화했습니다.
=> [Feat] Comment mock API 구현 및 문서화

back/src/main/java/travelRepo/domain/account/controller/AccountController.java, back/src/main/java/travelRepo/domain/account/service/AccountService.java, back/src/main/java/travelRepo/domain/board/controller/BoardController.java, back/src/main/java/travelRepo/domain/board/dto/BoardAddReq.java, back/src/main/java/travelRepo/domain/board/entity/Board.java, back/src/main/java/travelRepo/domain/board/entity/BoardPhoto.java, back/src/main/java/travelRepo/domain/board/entity/BoardTag.java, back/src/main/java/travelRepo/domain/board/entity/Tag.java, back/src/main/java/travelRepo/domain/board/repository/TagRepository.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/main/java/travelRepo/global/security/config/SecurityConfig.java, back/src/main/java/travelRepo/global/upload/service/LocalUploadService.java, back/src/main/java/travelRepo/global/upload/service/S3UploadService.java, back/src/main/java/travelRepo/global/upload/service/UploadService.java, back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
1. UploadService에서 발생하는 IOException이 Service와 Controller까지 올라오는 문제가 있어 UploadService 내에서 BusinessLogicException으로 처리했습니다.
2. 로컬 환경에서 이미지 파일에 접근할 수 있도록 권한을 수정했습니다.
3. 일부 엔티티에 필요한 어노테이션과 메서드를 추가했습니다.
4.  게시글 등록 API를 구현했습니다.
5. 게시글 등록 API 테스트 코드를 작성했습니다.
- 게시글 등록에 성공하는 경우와
- 입력으로 받는 파라미터의 validation에 실패하는 경우 두 가지 케이스에 대한 테스트를 작성했습니다.
=> [Feat] 게시글 등록 API 구현 및 테스트

front/src/component/common/button/ButtonStyle.js
버튼 3종류 스타일 추가했습니다.
기본버튼 : DefaultButton
아니오버튼: NegativButton
투명버튼: TransparentButton
=> [Feat] 버튼 스타일 3종류 추가

back/src/main/java/travelRepo/domain/account/entity/Account.java, back/src/main/java/travelRepo/domain/board/repository/BoardPhotoRepository.java, back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java, back/src/main/java/travelRepo/domain/board/repository/BoardTagRepository.java, back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java, back/src/main/java/travelRepo/domain/follow/controller/FollowController.java, back/src/main/java/travelRepo/domain/follow/dto/FollowPostRes.java, back/src/main/java/travelRepo/domain/follow/entity/Follow.java, back/src/main/java/travelRepo/domain/follow/repository/FollowRepository.java, back/src/main/java/travelRepo/domain/follow/service/FollowService.java, back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/test/java/travelRepo/domain/follow/controller/FollowControllerTest.java
Follow API을 구현했습니다.
추가 변경
1. bulk delete 메서드에 clear 옵션이 불필요하기 때문에 해당 옵션을 제거하였습니다.
=> [Feat] Follow API 구현

front/src/component/common/button/ButtonStyle.js, front/src/component/common/header/Header.jsx, front/src/component/common/header/HeaderUser.jsx, front/src/component/common/header/Search.jsx
- 헤더 컴포넌트 작업
- 버튼 컴포넌트 font-weight 추가
=> [Feat] 헤더 컴포넌트 작업 및 버튼 옵션 추가

front/src/component/common/footer/Footer.jsx
=> [Feat] Footer 컴포넌트 작업 및 반응형 적용

back/src/main/java/travelRepo/domain/board/controller/BoardController.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java, back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java, back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java, back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java, back/src/test/resources/static/db/data.sql
1. 게시글 삭제 API 구현 및 테스트 코드를 작성했습니다.
2. 게시물 수정에서 db 조회시 잘못된 메서드를 사용해 수정했습니다.
=> [Feat] 게시글 삭제 API 구현 및 테스트

back/src/main/java/travelRepo/domain/likes/controller/LikesController.java, back/src/main/java/travelRepo/domain/likes/dto/LikesCheckRes.java, back/src/main/java/travelRepo/domain/likes/dto/LikesPostRes.java, back/src/main/java/travelRepo/domain/likes/entity/Likes.java, back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java, back/src/main/java/travelRepo/domain/likes/service/LikesService.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/test/java/travelRepo/domain/likes/controller/LikesControllerTest.java
Likes API 구현 및 Test를 작성했습니다.
Follow와 로직이 사실상 같습니다. 
다만 Follow는 자기자신을 Follow할 수 없지만 Likes같은 경우에는 자추가 가능하도록 해놨습니다.
추가 변경
1. ExceptionCode 문구를 한글로 통일했습니다.
=> [Feat] Likes API 구현 및 Test

front/src/component/common/header/Header.jsx, front/src/component/main/MainContents.jsx, front/src/component/main/MainSort.jsx, front/src/component/main/MainTheme.jsx
- 헤더와 메인이 겹치는 현상 수정
- 메인 테마가 고정되도록 수정
=> [Refactor] 헤더와 메인이 겹치는 현상 수정

front/src/component/publish/PublishForm.jsx, front/src/component/publish/categoryData.jsx, front/src/pages/PublishPage.jsx
*통신연결/세부 유효성검사 추후 구현
11/15~16(수)
=> [Feat] 게시글 작성화면 페이지 목업 구현

back/src/main/java/travelRepo/domain/comment/controller/CommentController.java, back/src/main/java/travelRepo/domain/comment/dto/CommentModifyReq.java, back/src/main/java/travelRepo/domain/comment/entity/Comment.java, back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java, back/src/main/java/travelRepo/domain/comment/service/CommentService.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java
=> 댓글 수정 API 구현 및 테스트

front/src/action/loginAsync.js, front/src/api/loginApi.js, front/src/index.js, front/src/redux/loginSlice.js, front/src/redux/store.js
- slice 기초세팅
- action 기초세팅
- api 기초세팅
- store 기초세팅
=> [FE] 상태관리 초기세팅

back/src/main/java/travelRepo/domain/comment/controller/CommentController.java, back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java, back/src/main/java/travelRepo/domain/comment/service/CommentService.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/test/java/travelRepo/domain/comment/controller/CommentControllerTest.java, back/src/test/resources/static/db/data.sql
=> [Feat] 댓글 삭제 API 구현 및 테스트

back/src/main/java/travelRepo/domain/board/controller/BoardController.java, back/src/main/java/travelRepo/domain/board/dto/BoardSummaryRes.java, back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java
검색/필터 기능이 없는 단순한 전체 조회 기능을 구현했습니다.
=> [Feat] 게시물 전체 조회 API 구현

front/.gitignore, front/src/setupProxy.js
- 프록시 초기 세팅
- .env 파일 생성 및 ignore 처리
=> [FE] 프록시 세팅

front/src/component/common/Post.jsx
- **기존**
태그 길이가 길어질 경우 유저네임이 줄바꿈 되므로 스켈레톤을 맞춰 적용하는데 어려움이 있음
- **수정**
유저네임이 처음부터 아래쪽에 위치하도록 배치함
=> [Refactor] Post 레이아웃 재조정

back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java, back/src/test/resources/static/db/data.sql
board 쪽 테스트를 통과하도록 수정하였고 testImg 폴더가 git에 누락되어서 새로 추가하였습니다.
=> [Chore] test 수정 및 testImg 폴더 추가

front/src/component/common/like/Like.jsx, front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/PostDetailMain.jsx, front/src/component/postDetail/PostDetailPhoto.jsx, front/src/component/postDetail/PostMockData.js, front/src/pages/PostDetailPage.jsx
- #108
- #68 
좋아요 컴포넌트 수정 : 글씨도 같이 색상 변경 되도록 수정 / 아이콘-글씨간 간격 입력 추가 (기존 : 10px고정)
=> [Feat] 게시글 상세화면 본문 컴포넌트 레이아웃/스타일 적용

back/src/main/java/travelRepo/domain/account/dto/AccountModifyReq.java, back/src/main/java/travelRepo/domain/account/repository/AccountRepository.java, back/src/main/java/travelRepo/domain/account/service/AccountService.java, back/src/main/java/travelRepo/global/exception/ExceptionCode.java, back/src/main/java/travelRepo/global/exception/advice/ExceptionAdvice.java, back/src/main/java/travelRepo/global/exception/dto/ErrorResponse.java, back/src/main/java/travelRepo/global/security/filter/JwtAuthenticationFilter.java, back/src/main/java/travelRepo/global/security/handler/AccountAccessDeniedHandler.java, back/src/main/java/travelRepo/global/security/handler/AccountAuthenticationEntryPoint.java, back/src/test/java/travelRepo/domain/account/controller/AccountControllerTest.java
nickname 중복 설정, 에러 코드를 추가하였습니다.
에러 코드는 기존 테스트 코드나 다른 코드에 영향이 가지않도록 하기 위해서 코드를 추가하는 방식을 사용했습니다.
추가 변경
1. 회원 수정시 비밀번호가 암호화되지 않아서 암호화하는 로직을 추가하였습니다.
=> [Fix] nickname 중복 설정, 에러 코드 추가

front/src/component/common/modal/YesNoModal.jsx
승목님 요청으로 YesNo모달의 예 버튼에 이벤트 함수 props를 추가했습니다.
이제 예 버튼은 modalActioner props로, 아니오 버튼은 modalCloser props로 내려주시면 됩니다.
=> [Feat] YesNo모달 예 버튼에 이벤트 props 추가

front/src/component/common/header/Header.jsx, front/src/component/common/like/Like.jsx, front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/PostDetailMain.jsx, front/src/component/postDetail/PostDetailPhoto.jsx, front/src/component/postDetail/comment/Comment.jsx, front/src/component/postDetail/comment/CommentDetail.jsx, front/src/component/postDetail/comment/CommentMore.jsx, front/src/component/postDetail/comment/CommentWrite.jsx, front/src/pages/PostDetailPage.jsx
- 댓글 컴포넌트 완성
- 게시글 상세화면 CSS 수정
- 헤더 max-width 추가
- like 공통 컴포넌트 변수 오류로 인한 수정
=> [Feat] 댓글 컴포넌트 개발 및 CSS 수정

front/src/App.js, front/src/component/common/Loading.jsx
- 동적 라우팅 적용 Suspense를 사용해서 로딩 컴포넌트 적용
- 초기 디폴트 페이지 삭제
=> [FE] 페이지 라우팅 및 로딩 컴포넌트 적용

front/src/App.js, front/src/pages/PostDetailPage.jsx
App.js에 헤더 추가하고 PostDetailPage에서 헤더 제거했습니다.
=> [Layout] App.js에 헤더 추가

back/src/main/java/travelRepo/domain/board/entity/Board.java, back/src/main/java/travelRepo/domain/likes/service/LikesService.java
likes에 따라서 board의 likeCount가 변경되도록 수정하였습니다.
=> [Fix] likes 시, board의 likeCount 변경되도록 수정

front/src/component/postDetail/PostDetailMain.jsx, front/src/component/postDetail/PostDetailPhoto.jsx, front/src/component/postDetail/comment/Comment.jsx
1. 이미지 캐러셀 적용
2. 모바일 시 width 가 꽉차지 않아 100% 추가
###추후 작업
1. 현재 map의 인덱스로 처리를 하는 방식을 고유값을 사용하여 사용 예정
=> [FE] 게시글 상세화면 이미지 캐러셀 적용

back/src/main/java/travelRepo/domain/account/controller/AccountController.java, back/src/main/java/travelRepo/domain/account/dto/AccountModifyReq.java, back/src/main/java/travelRepo/domain/account/service/AccountService.java, back/src/test/java/travelRepo/domain/account/controller/AccountControllerTest.java
사진을 별도로 저장하는 API를 만들었기 때문에 회원 프로필 수정 시 파일이 아닌 주소를 받도록 API를 변경하였습니다.
=> [Fix] 회원 수정 API, Test 변경

back/src/main/java/travelRepo/domain/comment/controller/CommentController.java, back/src/main/java/travelRepo/global/image/repository/FolderImageRepository.java, back/src/main/java/travelRepo/global/image/repository/S3ImageRepository.java
1. 댓글이 최신 순으로 정렬되도록 default 값을 변경했습니다. 
2. ImageRepository 어노테이션이 @Service로 되어있어 @Repository로 변경했습니다. 혹시 누락된게 아니라 의도하신거라면 다시 수정하겠습니다.
=> [Fix] 댓글 default 정렬 기준 변경

front/src/api/signupApi.js, front/src/component/common/modal/LoginModal.jsx, front/src/component/common/modal/SignupModal.jsx
로그인 및 회원가입 유효성 검사 업데이트
로그인 인풋이 공란이면 로그인 요청 전에 유효성검사처리를 하도록 했습니다.
회원가입 시 중복 닉네임을 혀용하지 않습니다.
=> [Feat] 로그인 및 회원가입 유효성 검사 업데이트

front/src/api/publishApi.js, front/src/api/publishPostApi.js, front/src/component/publish/PublishForm.jsx, front/src/component/publish/PublishPhoto.jsx, front/src/component/publish/categoryData.jsx
어제 멘토링 시간때 사용한 브랜치인데 머지 부탁드립니다.
내용요약 : 페이지 내 기능 최적화, 통신 연결 로직 구현 등
TODO : 이미지 등록 & 유효성검사 (작업중)
=> [FE] 게시글 작성 페이지 기능 추가

front/src/api/postDetailApi.js, front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/comment/Comment.jsx, front/src/component/postDetail/comment/CommentDetail.jsx, front/src/component/postDetail/comment/CommentMore.jsx, front/src/component/postDetail/comment/CommentWrite.jsx, front/src/index.js
###작업목록
1. 게시글 상세화면 반응형에 맞게 CSS 수정
2. 댓글 CRUD
3. 댓글 무한스크롤
=> [FE] 댓글 CRUD 및 무한스크롤

front/src/component/userInfo/UserInfo.js, front/src/component/userInfo/UserInfoAvatar.js, front/src/component/userInfo/UserInfoCard.js, front/src/component/userInfo/UserInfoTab.js
아까 공유해드리기로 한 유저정보 컴포넌트입니다.
반응형 등 세부적인 부분은 미구현이고 마음대로 수정 하셔도 됩니다.
구조는 UserInfo에 Card랑 Tab으로 나뉘놨어요
=> [Feat] 사용자 정보 컴포넌트

front/src/component/publish/PublishForm.jsx
- 제목 : 5자이상 ~ 40자이하 (필수)
- 본문 : 5자이상 ~ 제한없음 (필수)
- 위치 : ~ 40자이하 (선택)
- 카테고리 : 택1 (필수)
- 태그 : 5개까지 (글자수 6자 이하, 선택)
- 사진 : 1장 이상 (필수) <= TODO
글자수에 공백은 일단 포함이고
조건 충족 안되면 전송불가입니다
=> [Feat] 게시글 작성 페이지 유효성 검사 업데이트

front/src/api/postPhotoApi.js, front/src/component/publish/PublishPhoto.jsx, front/src/setupProxy.js
프록시에 /image-files 엔드포인트 추가
사진 업로드 후 url 받아오는 기능 추가
=> [Feat] 사진 업로드 후 url 받아오는 기능 추가

front/src/component/common/header/HeaderDropDownBox.jsx, front/src/component/common/header/HeaderDropDownItem.jsx, front/src/component/common/header/HeaderUser.jsx, front/src/component/main/MainTheme.jsx
1. 드롭다운 박스 개발
2. 헤더에 드롭다운 박스 적용
3. 테마 z-index 9로 수정 ( 이유 : 드롭다운과 테마가 겹치는 현상으로 인하여 수정)
=> [FE] 드롭다운 박스 개발 및 적용

back/src/main/java/travelRepo/domain/board/dto/BoardDetailsRes.java, back/src/main/java/travelRepo/domain/board/entity/Board.java, back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java, back/src/main/java/travelRepo/domain/comment/repository/CommentRepository.java, back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
동시성 문제를 고려하여 조회수 증가 로직을 직접 쿼리문을 날리는 방식으로 수정했습니다.
=> [Fix] 조회수 증가 로직 변경 및 기타 수정

front/src/api/postDetailApi.js, front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/comment/CommentWrite.jsx
###작업목록
1. 댓글 빈칸 등록 방지
2. 자신의 게시글 수정 삭제 안보이는 부분 수정
3. toast 오른쪽 이동
4. 태그 $ 삭제
=> [FE] 게시글 삭제 오류 수정

front/src/api/publishApi.js, front/src/component/publish/PublishForm.jsx, front/src/component/publish/PublishPhoto.jsx
사진 편집창에서 개별 추가/삭제가 가능합니다
혼자 구현 했을때 사진이 미리보기에선 사라지는데 글 등록하면 그대로 있어서 힘들었는데요.
규식님 @starplanter93👍 께서 로직짜는데 큰 도움 주셔서 잘 해결 되었네요 감사합니다.
등록 테스트 해보시고 개선할 부분 있으시면 말씀주세요 
위치 태그만 선택이고 나머지는 필수에요
TODO : css개선ㅠㅠ + 글 등록 시 홈 말고 작성한 글로 이동하도록 변경
=> [Feat] 게시글 작성 페이지 이미지 개별 삭제 기능

front/src/component/common/header/HeaderUser.jsx
=> [Feat] 게시글 작성 페이지 헤더 연결

back/build.gradle, back/src/main/java/travelRepo/TravelRepoApplication.java, back/src/main/java/travelRepo/domain/account/service/AccountService.java, back/src/main/java/travelRepo/domain/follow/service/FollowService.java, back/src/main/java/travelRepo/global/config/CacheConfig.java, back/src/main/java/travelRepo/global/config/RedisConfig.java, back/src/main/resources/application-server.yml, back/src/test/resources/application.yml
Account 조회에 redis 기반 캐싱을 적용했습니다
=> [Feat] Account 조회 캐싱 적용

front/src/api/myPostApi.js, front/src/component/userInfo/UserInfoTab.jsx, front/src/pages/myPages/MyPost.jsx
내정보 - 게시글 탭 승민님이 주신 무한스크롤 훅 사용해서 완성했습니다.
유저정보의 게시글 탭 아이콘을 변경했습니다.
=> [Feat] 내정보 - 게시글 탭 구현

front/src/api/loginUserApi.js, front/src/component/common/header/HeaderDropDownItem.jsx, front/src/component/common/header/HeaderUser.jsx
로그인유저정보를 로컬스토리지에서 쿠키에 저장하도록 변경
=> [Fix] 로그인유저정보를 쿠키에 저장하도록 변경

back/src/main/java/travelRepo/domain/board/controller/BoardController.java, back/src/main/java/travelRepo/domain/board/repository/BoardRepository.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java, back/src/main/java/travelRepo/domain/likes/likesRepository/LikesRepository.java
유저가 좋아요한 게시글을 조회하는 API가 없어 만들었습니다.
일단 없어서 급하게 만들었는데 먼저 PR하고 테스트&수정 하겠습니다.
=> [Feat] 좋아요한 게시글 조회 API 구현

front/src/App.js, front/src/component/common/header/Header.jsx, front/src/component/common/header/HeaderDropDownBox.jsx, front/src/component/common/header/HeaderDropDownItem.jsx, front/src/component/common/header/HeaderUser.jsx
1. 햄버거 버튼을 바라보는 옵저버 추가( 추가이유 : 페이지의 사이즈가 줄었다가 커질 때 해당 드롭다운 박스를 끄기 위함)
2. 드롭다운 박스에 로그인 및 회원가입 추가
3. 로그인 모달 slice화에 따른 App.js 수정
=> [Fix] 햄버거 박스 수정 및 기능 추가

front/src/api/userDataApi.js, front/src/component/userInfo/UserInfo.jsx, front/src/component/userInfo/UserInfoTab.jsx, front/src/pages/myPages/MyPost.jsx
UserInfo에서 사용하는 api 수정 및 팔로우 팔로잉 반영
=> [Feat] UserInfo에서 사용하는 api 수정 및 팔로우 팔로잉 반영

front/src/component/publish/PublishModalButton.jsx
경호님께서 댓글 등록창에 사용하신 토스트 디자인을 재활용 했습니다.
이미지 0장일때 👉 '사진을 1장 이상 업로드 하세요'
테마 미선택시 👉 '테마를 선택하세요' (수정창은 무조건 선택되서 해당없음)
감사합니다
@hipopotamus
=> [Feat] 글 작성/수정 페이지 toast 구현

front/src/component/postDetail/comment/CommentWrite.jsx
=> [Fix] 디바운스 딜레이 0.2초로 변경

front/src/api/followDataApi.js, front/src/pages/myPages/MyFollower.jsx, front/src/pages/myPages/MyFollowing.jsx
followDataApi 에서 page와 following인지 follower 인지 스테이터스 정해주면 데이터 받아옵니다.
해당 api로 받아온 데이터들은 MyFollower, MyFollowing 에서 받을 수 있게 해두었습니다.
=> [Feat] 팔로우 데이터 axios 작성 및 각 페이지에 내려주기

front/src/component/follow/FollowList.jsx, front/src/component/follow/FollowPost.jsx, front/src/pages/myPages/MyFollower.jsx
- 팔로워, 팔로잉 탭에서 사용할 컴포넌트 추가
- 컴포넌트 레이아웃, 스타일 적용
=> [Feat] 팔로워 탭 레이아웃 및 스타일 적용

front/src/component/publish/PublishPhoto.jsx
미리보기도 1장당 최대 10MB까지만 등록 가능하도록 바꿨습니다.
이제 큰 파일 등록하면 업로더 하단에 에러 메세지 뜹니다.
10MB 이미지 없으시면 MAX_SIZE_MB 변수에 작은 숫자 할당해서 테스트 해보시면 될거에요.
=> [Feat]이미지 첨부 용량 제한 추가

back/src/docs/asciidoc/index.adoc, back/src/main/resources/static/docs/index.html, back/src/test/java/travelRepo/domain/board/controller/BoardControllerTest.java
=> [Docs] API 명세서 수정

front/src/api/postDetailApi.js, front/src/component/common/header/Search.jsx, front/src/component/postDetail/comment/CommentWrite.jsx, front/src/hooks/useIntersect.js, front/src/pages/mainPages/AllThemePage.jsx, front/src/pages/mainPages/RestaurantPage.jsx, front/src/pages/mainPages/SpotPage.jsx, front/src/pages/mainPages/StayPage.jsx, front/src/redux/searchSlice.js, front/src/redux/store.js
1. 검색 기능 추가
2. 정렬 중복 으로 누르지 않게하는 부분 미흡해서 수정
검색을 진행하면 해당 테마에서 검색이 진행되며 다른 테마로 이동해도 자신이 검색한 키워드를 가지고 검색을 진행하게 된다.
1. 상세화면에서 이전페이지로 이동하더라도 정렬을 기억할 수 있도록 한다.
2. 상세화면과 같은곳에서 검색을 진행할 때 안되는 부분이 있었는데 해당 부분 검색 가능하도록 변경
3. 이에 따른 searchSlice 값 추가
검색 기능을 사용하시면서 오류가 발생하는 부분이 있다면 알려주세요
=> [Feat] 검색기능 추가

front/src/component/common/header/Header.jsx, front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/comment/Comment.jsx, front/src/component/postDetail/comment/CommentWrite.jsx, front/src/hooks/useIntersect.js, front/src/pages/mainPages/AllThemePage.jsx, front/src/pages/mainPages/RestaurantPage.jsx, front/src/pages/mainPages/SpotPage.jsx, front/src/pages/mainPages/StayPage.jsx
1. 메인 로고 Link에서 a tag로 변경
2. page 미사용으로 인한 use옵저버 수정
3. 댓글 250자 제한 적용
4. 댓글 카운트 추가
5. 댓글 전체 높이 수정(총 3개가 바로 보이게 변경)
6. 콘텐츠 무너지는 부분 수정
7. 사용자 이미지에 링크 적용
=> [Fix] 상세 페이지 수정 및 연결 

front/src/assets/GlobalStyle.js, front/src/component/main/MainSort.jsx
선택된 sort 메뉴에 active 스타일을 추가했습니다.
=> [Refactor] 메인페이지 sort 메뉴 active 스타일 추가

front/src/assets/GlobalStyle.js, front/src/component/common/Pagination.jsx, front/src/pages/myPages/MyFollower.jsx, front/src/pages/myPages/MyFollowing.jsx
- 페이지네이션 UI (디자인에 소질이 없어서 트립닷컴이랑 똑같이 만들어봤습니다😅)
- 페이지네이션 버튼 로직 구현
- 팔로워, 팔로잉 페이지에 페이지네이션 연결
무지성으로 코딩하다가 커밋을 많이 못했습니다😭
=> [Feat] 페이지네이션 구현 및 팔로워, 팔로잉 페이지에 연결

front/src/pages/myPages/MyLikes.jsx, front/src/pages/myPages/MyPost.jsx
변경된 useIntersect에 맞춰 내정보-게시글, 좋아요탭 수정
경호님이 잘 만들어주셔서 어려움없이 수정했습니다.
=> [Fix] 변경된 useIntersect에 맞춰 내정보-게시글, 좋아요탭 수정

front/src/App.js, front/src/component/common/modal/LoginModal.jsx, front/src/component/common/modal/SignupModal.jsx, front/src/redux/loginModalSlice.js
회원가입 모달 팝업시 로그인 모달 내려가도록 수정
회원가입모달은 이제 App.js와 슬라이스를 통해 전역으로 관리합니다.
로그인 모달에서 회원가입 버튼 누를 시, 회원가입 모달이 열리면서 로그인모달은 내려갑니다.
그리고 로그인 성공 시, 잠깐 뜨던 로그인 토스트 삭제 했습니다.
=> [Fix] 회원가입 모달 팝업시 로그인 모달 내려가도록 수정

front/src/component/publish/PublishForm.jsx, front/src/component/publish/PublishLocCat.jsx, front/src/component/publish/PublishModalButton.jsx, front/src/component/publish/PublishPhoto.jsx, front/src/component/publish/PublishTags.jsx
멘토님께 조언받은 부분이랑 필요하다고 생각되는 부분 보완 작업 진행했습니다.
- 테마 선택 방식 변경 (기존 : 투명도 조절 => 변경 : 색상 반전)
- 등록된 사진이 없을땐  업로더 창만 떠있게 & 업로더 hover 효과
- 모바일 모드 사진 여러장 등록시 자연스럽게 배열
- 태그 추가 유효성 검사 메세지 화면 출력, 속도 개선 등
- 필수 필드 표기 & 토스트 알림창 적용
- 게시글 길이 제한 설정(2,000자)
- 게시글 등록 완료 후 페이지 넘어가는 시간 단축
Todo : 수정 페이지 진입시 테마 탭의 색상이 active되어있도록 변경
=> [Feat] 게시글 작성 기능 보완

front/src/component/common/header/HeaderDropDownBox.jsx, front/src/component/common/header/HeaderUser.jsx
=> [Fix] 이미지 비정상적으로 동작되던거 수정

front/src/component/postDetail/PostDetailArticle.jsx, front/src/component/postDetail/PostDetailMain.jsx, front/src/component/postDetail/PostDetailPhoto.jsx, front/src/component/postDetail/comment/Comment.jsx
=> [Fix] 게시글 상세화면 반응형 수정

back/src/main/java/travelRepo/global/image/service/ImageService.java
=> [Fix] 잘못된 merge 수정

front/.eslintrc.js, front/src/component/common/header/HeaderDropDownBox.jsx, front/src/component/common/header/HeaderDropDownItem.jsx, front/src/component/userInfo/UserInfoCard.jsx
=> [Fix] 타회원정보에서 내정보로 이동 시, 랜더링 버그 수정

front/package-lock.json, front/package.json, front/src/hooks/useIntersect.js, front/src/index.js
1. sentry 적용
2. 옵저버 부분에만 sentry 적용
추후 전체 적용 예정
=> [Feat] sentry 적용

front/src/component/common/header/HeaderUser.jsx, front/src/hooks/useIntersect.js, front/src/pages/mainPages/AllThemePage.jsx, front/src/pages/mainPages/RestaurantPage.jsx, front/src/pages/mainPages/SpotPage.jsx, front/src/pages/mainPages/StayPage.jsx
1. 빈칸도 검색 가능하도록 변경
2. use옵저버에서 lastData 초기화 함수 return문 추가
3. 정렬 및 검색 시 lastData 초기화 안되는 부분 수정
4. 헤더 이미지 CSS 수정
=> [FE] 헤더 이미지 수정 및 검색 기능 수정

front/src/api/deleteUserApi.js, front/src/component/myInfoEdit/MyInfoEditContent.jsx, front/src/component/myInfoEdit/MyinfoEditDelete.jsx
회원탈퇴 기본 기능을 구현했습니다.
버튼 위치는 내 정보 수정 페이지 잘 찾아 보시면 있습니다.
세번 물어보고 전부 동의하면 탈퇴 됩니다.
탈퇴 시 게시물 전부 사라지니 새 계정 생성해서 테스트 해주세요!
=> [Feat] 회원탈퇴 기능 추가

front/src/component/postDetail/PostDetailMain.jsx, front/src/component/postDetail/comment/CommentWrite.jsx
1. 댓글 로딩스피너 변경
2. 상세 페이지 게시물이 존재 하지 않을시 에러페이지로 연결
=> [FE] 게시글 상세페이지 댓글 로딩 스피너 변경 및 에러 페이지 연결

front/src/component/myInfoEdit/MyInfoEditContent.jsx
1. 사용자 정보에서 이미지 수정시 헤더에서 이미지도 변경되도록 수정
=> [Fix] 사용자 정보 수정시 이미지 변경 안되는 부분 수정

front/src/component/myInfoEdit/MyInfoEditContent.jsx
=> [Fix] Eslint오류 수정

front/src/App.js, front/src/api/tempPasswordApi.js, front/src/component/common/modal/FindPasswordModal.jsx, front/src/component/common/modal/LoginModal.jsx, front/src/component/common/modal/ModalCard.jsx, front/src/component/common/modal/SignupModal.jsx, front/src/redux/loginModalSlice.js
=> [Feat] 비밀번호 찾기 모달 - 임시비밀번호 발급 기능 구현

front/src/api/tempPasswordApi.js
=> [Fix] 임시비밀번호 발급 버그 수정

front/src/component/common/header/HeaderDropDownBox.jsx
1. 햄버거 박스 회원가입 모달 꺼지지 않던 부분 수정
=> [Fix] 회원가입 Slice화에 따른 수정

front/src/api/tempPasswordApi.js, front/src/component/userInfo/UserInfoAvatar.jsx
=> [Feat] 회원정보페이지 유저카드 아바타 디폴트 이미지 추가

back/src/main/java/travelRepo/domain/account/controller/AccountEmailController.java, back/src/main/java/travelRepo/domain/board/repository/BoardRepositoryImpl.java, back/src/main/java/travelRepo/domain/board/service/BoardService.java, back/src/main/resources/application-server.yml, back/src/main/resources/templates/mail/passwordEx.html, back/src/main/resources/templates/mail/simple-link.html, back/src/test/java/travelRepo/domain/account/controller/AccountEmailControllerTest.java
1. 무한 스크롤 기존 페이지네이션 방식을 삭제했습니다. 
2. 임시 비밀번호 발급 메일 내용을 수정했습니다.
3. 게시글 전체 조회 시 NullpointException이 발생할 수 있는 부분을 수정헀습니다.
=> [Fix] 백엔드 수정사항

front/src/api/postDetailApi.js, front/src/component/postDetail/comment/Comment.jsx, front/src/component/postDetail/comment/CommentWrite.jsx
1. 댓글 최대 6개 보이도록 수정
2. 요청 댓글 개수 6개로 수정
=> [FE] 보이는 댓글 수 수정

front/src/component/postDetail/comment/CommentMore.jsx
=> [Feat] 댓글 이미지 클릭시 해당 유저페이지로 이동

front/src/component/publish/PublishForm.jsx, front/src/component/publish/PublishLocCat.jsx, front/src/component/publish/PublishModalButton.jsx, front/src/component/publish/PublishPhoto.jsx, front/src/component/publish/PublishTags.jsx
- 대표사진 썸네일 추가
- 수정페이지 테마 선택되어있도록 수정
- 본문 에러 메세지 추가
- 작성/수정 후 모달 작동방식 변경
- 게시물 등록 연타 중복 방지
=> [Feat] 글작성/수정페이지 수정사항 반영

back/src/main/java/travelRepo/global/config/WebConfig.java, back/src/main/java/travelRepo/global/security/config/SecurityConfig.java, back/src/main/java/travelRepo/global/security/jwt/JwtProcessor.java, back/src/main/resources/application-dev.yml, back/src/main/resources/application-server.yml, back/src/main/resources/application-service.yml, back/src/test/resources/application.yml
1. Cors 설정을 변경했습니다. 
2. 배포용 서버 설정파일과 개발용 설정파일을 분리했습니다.
=> [Fix] 배포 관련 수정

front/src/component/common/Pagination.jsx
현재 페이지를 눌렀을 때 발생되는 무한로딩 현상 수정하였습니다.
=> [Fix] 현재 페이지를 눌렀을 때 발생되는 무한로딩 현상 수정

back/src/main/java/travelRepo/domain/account/service/AccountEmailService.java
임시 비밀번호 url에서 /가 중복되는 부분을 수정하였습니다.
=> [Fix] 임시 비밀번호 변경 url 수정

back/src/main/java/travelRepo/domain/account/service/AccountEmailService.java
=> [BUG] 임시 비밀번호 변경 적용

back/src/main/java/travelRepo/domain/account/service/AccountEmailService.java
=> [Bug] 임시 비밀번호 url 변경

back/src/main/java/travelRepo/domain/account/controller/AccountEmailController.java
임시 비밀번호 변경 에러 페이지 url을 변경했습니다.
=> [Bug] 임시 비밀번호 변경 에러 페이지 url 변경

back/build.gradle, back/src/main/java/travelRepo/global/security/config/SecurityConfig.java, back/src/main/java/travelRepo/global/security/handler/OauthAccountSuccessHandler.java, back/src/main/resources/application-dev.yml, back/src/main/resources/application-server.yml, back/src/main/resources/application-service.yml, front/.idea/inspectionProfiles/Project_Default.xml
Google OAuth 기능을 추가하였습니다!
OAuth를 통해 인증에 성공하면 OAuthAccoutSuccessHandler에서 처리가 되게 됩니다.
OAuthAccoutSuccessHandler에서는 Authentication을 통해 Google에서 인증후 보내지는 사용자의 정보를 조회할 수 있습니다.
사용자 정보를 통해 DB에 있는 회원이면 이메일로 회원을 조회, DB에 없다면 DB에 등록후, 회원을 조회해서 JWT를 생성합니다.
이후에는 JWT를 프런트쪽으로 리다이렉트해서 보낸 후 프런트쪽에서 로그인 처리가 진행됩니다.
=> [Feat] Google OAuth 기능 추가

back/src/main/java/travelRepo/global/security/config/SecurityConfig.java, back/src/test/resources/application.yml
회원 등록 인증을 허가하는 코드가 누락되서 추가하였습니다.
테스트코드에 OAuth 설정이없어서 오류가났기 때문에 설정을 추가하였습니다.
=> [Fix] 회원 등록 인증 허가 누락 수정

front/src/component/common/modal/SignupModal.jsx
회원가입 닉네임 유효성검사 추가
2자 이상 20자 이하만 가능하게 했습니다.
=> [Feat] 회원가입 닉네임 유효성검사 추가

back/src/main/java/travelRepo/global/security/handler/OauthAccountSuccessHandler.java
프런트에서 제공하는 uri에 맞춰 OAuth 인증 리다이렉트 주소를 변경 하였습니다.
=> [Fix] OAuth 인증 리다이렉트 주소 변경

front/src/hooks/useIntersect.js
=> [Fix] Search 검색어 인코딩 작업

front/src/component/publish/PublishModalButton.jsx, front/src/component/publish/PublishPhoto.jsx
=> [Feat] 글등록에러 토스트 추가, 중복등록 방지, 기타UI수정 등

front/src/component/common/modal/LoginModal.jsx
=> [Fix] Oauth 주소 변경

front/src/api/postPhotoApi.js, front/src/component/myInfoEdit/MyInfoEditProfile.jsx, front/src/component/publish/PublishForm.jsx, front/src/component/publish/PublishLocCat.jsx, front/src/component/publish/PublishPhoto.jsx
- 깜빡임 수정 : uuid 대신 url을 활용해 key 값을 생성하는 방식으로 변경
(e.g. 84e0b7JPG, 2ef906a3ff)
- css 리팩토링 : 가독성 향상을 위해 미리보기/업로드 버튼 등 컴포넌트화 및 전체적으로 수정
- 주석 수정 : 불필요한 주석 제거, 위치 변경
=> [Fix] 이미지 미리보기 깜빡임 수정 및 기타 리팩토링

front/src/hooks/useIntersect.js, front/src/index.js
=> [Refactor] Sentry 제거
